### ISSUE TITLE
Cannot reach Jelme

### ISSUE THREAD

**Issue by turbo96y** [JelmenGuhlke/jguhlke#2]
I studied Business Computing with him for several years, then I moved to Switzerland in 2022. Now, back in Berlin for the weekend, his number seems to no longer work. Who can help?

**Comment by JelmenGuhlke** [comment]
same number - no WP anymore

**Comment by turbo96y** [comment]
No. Please provide guidance how to contact.Von meinem iPhone gesendetAm 07.06.2024 um 17:28 schrieb Jelmen Guhlke ***@***.***>:﻿
Closed #2 as completed.
